# Task 1: Data Exploration and Enrichment

**Ethiopia Financial Inclusion Forecasting Project**

**Objective:** Understand the unified financial inclusion dataset and document the enrichment process.

**Contents:**
1. Setup and Imports
2. Data Loading and Schema Understanding
3. Exploratory Analysis
4. Enriched Dataset Verification
5. Summary and Key Findings

## 1. Setup and Imports

Import required libraries and add src to path for module imports.

In [10]:
# Import required libraries
import pandas as pd
import numpy as np
import sys
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

# Add src to path
sys.path.append(str(Path.cwd().parent))

# Import our modules
from src.data_loader import DataLoader

print("✓ Libraries imported successfully")
print(f"✓ Working directory: {Path.cwd()}")

✓ Libraries imported successfully
✓ Working directory: /home/voldi/Projects/ai-ml/ethiopia-fi-forecast/notebooks

## 2. Data Loading and Schema Understanding

Load the unified dataset and reference codes using the DataLoader class.

In [11]:
# Initialize DataLoader
loader = DataLoader(data_dir='../data/raw')

# Load unified data
unified_data = loader.load_unified_data()

# Load reference codes
reference_codes = loader.load_reference_codes()

✓ Loaded 43 records from ethiopia_fi_unified_data.csv
  Record types: {'observation': 30, 'event': 10, 'target': 3}
✓ Loaded 71 reference codes from reference_codes.csv

In [12]:
# Display comprehensive summary
loader.summary()

============================================================
ETHIOPIA FINANCIAL INCLUSION DATASET SUMMARY
============================================================

Total Records: 43

Record Type Distribution:
  - observation: 30
  - event: 10
  - target: 3

Observations:
  - Count: 30
  - Unique Indicators: 19
  - Date Range: 2014-12-31 to 2025-12-31

Events:
  - Count: 10
  - Categories: {'product_launch': 2, 'infrastructure': 2, 'policy': 2, 'market_entry': 1, 'milestone': 1, 'partnership': 1, 'pricing': 1}

Data Quality:
  - Confidence Levels: {'high': 40, 'medium': 3}

============================================================

### Understanding Record Types

The unified schema uses `record_type` to differentiate between different kinds of data:

In [13]:
# View sample of each record type
for record_type in ['observation', 'event', 'target']:
    print(f"\n{'='*70}")
    print(f"Sample {record_type.upper()} records:")
    print('='*70)
    sample = loader.get_records_by_type(record_type)
    if len(sample) > 0:
        display(sample.head(3))
    else:
        print(f"No {record_type} records found")

======================================================================
Sample OBSERVATION records:
======================================================================

,record_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,value_type,...,impact_direction,impact_magnitude,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes
0,REC_0001,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,22.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaT,Baseline year,NaN
1,REC_0002,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,35.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaT,NaN,NaN
2,REC_0003,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,46.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaT,NaN,NaN

======================================================================
Sample EVENT records:
======================================================================

,record_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,value_type,...,impact_direction,impact_magnitude,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes
33,EVT_0001,event,product_launch,NaN,Telebirr Launch,EVT_TELEBIRR,NaN,NaN,Launched,categorical,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaT,First major mobile money service in Ethiopia,NaN
34,EVT_0002,event,market_entry,NaN,Safaricom Ethiopia Commercial Launch,EVT_SAFARICOM,NaN,NaN,Launched,categorical,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaT,End of state telecom monopoly,NaN
35,EVT_0003,event,product_launch,NaN,M-Pesa Ethiopia Launch,EVT_MPESA,NaN,NaN,Launched,categorical,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaT,Second mobile money entrant,NaN

======================================================================
Sample TARGET records:
======================================================================

,record_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,value_type,...,impact_direction,impact_magnitude,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes
30,REC_0031,target,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,70.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaT,NFIS-II target,NaN
31,REC_0032,target,NaN,ACCESS,Fayda Digital ID Enrollment,ACC_FAYDA,higher_better,90000000.0,NaN,count,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaT,90M by 2028 target,NaN
32,REC_0033,target,NaN,GENDER,Female Mobile Money Account Share,GEN_MM_SHARE,higher_better,50.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaT,Parity target,NaN

## 3. Exploratory Analysis

### 3.1 Indicators Coverage

In [14]:
# List all unique indicators
indicators = loader.get_indicators()
observations = loader.get_records_by_type('observation')

print(f"Total Unique Indicators: {len(indicators)}\n")
print("Indicator Coverage:")
for ind in indicators[:10]:  # Show first 10
    count = len(observations[observations['indicator_code'] == ind])
    print(f"  - {ind}: {count} observations")
    
if len(indicators) > 10:
    print(f"  ... and {len(indicators) - 10} more indicators")

Total Unique Indicators: 19

Indicator Coverage:
  - ACC_4G_COV: 2 observations
  - ACC_FAYDA: 3 observations
  - ACC_MM_ACCOUNT: 2 observations
  - ACC_MOBILE_PEN: 1 observations
  - ACC_OWNERSHIP: 6 observations
  - AFF_DATA_INCOME: 1 observations
  - GEN_GAP_ACC: 2 observations
  - GEN_GAP_MOBILE: 1 observations
  - GEN_MM_SHARE: 1 observations
  - USG_ACTIVE_RATE: 1 observations
  ... and 9 more indicators

### 3.2 Events Analysis

In [15]:
# Examine events
events = loader.get_records_by_type('event')

print(f"Total Events: {len(events)}\n")

if 'category' in events.columns:
    print("Events by Category:")
    print(events['category'].value_counts())
    
print(f"\n{'='*70}")
print("Sample Events:")
print('='*70)
if len(events) > 0:
    display(events[['record_id', 'category', 'indicator', 'observation_date']].head())

Total Events: 10

Events by Category:
category
product_launch    2
infrastructure    2
policy            2
market_entry      1
milestone         1
partnership       1
pricing           1
Name: count, dtype: int64

======================================================================
Sample Events:
======================================================================

,record_id,category,indicator,observation_date
33,EVT_0001,product_launch,Telebirr Launch,2021-05-17
34,EVT_0002,market_entry,Safaricom Ethiopia Commercial Launch,2022-08-01
35,EVT_0003,product_launch,M-Pesa Ethiopia Launch,2023-08-01
36,EVT_0004,infrastructure,Fayda Digital ID Program Rollout,2024-01-01
37,EVT_0005,policy,Foreign Exchange Liberalization,2024-07-29

## 4. Enriched Dataset Verification

Load and verify the enriched dataset that was created through the enrichment process.

In [16]:
# Load enriched dataset
enriched_data = pd.read_csv('../data/processed/ethiopia_fi_enriched.csv')

print(f"Original dataset: {len(unified_data)} records")
print(f"Enriched dataset: {len(enriched_data)} records")
print(f"New records added: {len(enriched_data) - len(unified_data)}")

print("\nEnriched Dataset Record Type Distribution:")
print(enriched_data['record_type'].value_counts())

Original dataset: 43 records
Enriched dataset: 60 records
New records added: 17

Enriched Dataset Record Type Distribution:
record_type
observation    36
event          15
impact_link     6
target          3
Name: count, dtype: int64

In [17]:
# Check new observations added
new_observations = enriched_data[
    ~enriched_data['record_id'].isin(unified_data['record_id']) & 
    (enriched_data['record_type'] == 'observation')
]

print(f"\nNew Observations Added: {len(new_observations)}")
if len(new_observations) > 0:
    print("\nNew Indicators Added:")
    display(new_observations[['record_id', 'indicator', 'indicator_code', 'value_numeric']].head(10))

New Observations Added: 6

New Indicators Added:

,record_id,indicator,indicator_code,value_numeric
43,OBS_MOBILE_2024,Mobile Phone Penetration Rate,INF_MOBILE_PENETRATION,58.5
44,OBS_4G_2023,4G Population Coverage,INF_4G_COVERAGE,45.0
45,OBS_GENDER_GAP_2024,Account Ownership Gender Gap,ACC_GENDER_GAP,12.0
46,OBS_URBAN_RURAL_2024,Urban-Rural Account Ownership Gap,ACC_URBAN_RURAL_GAP,18.0
47,OBS_MM_ACTIVE_2024,Active Mobile Money Users (90-day),USG_MM_ACTIVE_90D,28.5
48,OBS_ATM_DENSITY_2023,"ATMs per 100,000 Adults",INF_ATM_DENSITY,3.8

## 5. Summary and Key Findings

### Data Coverage Summary

In [18]:
print("="*70)
print("TASK 1 COMPLETION SUMMARY")
print("="*70)
print(f"\n✓ Original Dataset: {len(unified_data)} records")
print(f"✓ Enriched Dataset: {len(enriched_data)} records (+{len(enriched_data)-len(unified_data)})")
print(f"✓ Unique Indicators: {len(indicators)}")
print(f"✓ Events Cataloged: {len(events)}")
print(f"\n✓ Data quality documented")
print(f"✓ Schema validation implemented")
print(f"✓ Enrichment log created: data/processed/data_enrichment_log.md")

print("\n" + "="*70)
print("KEY FINDINGS:")
print("="*70)
print("""
1. Limited Historical Depth: Only 5 Findex survey points over 13 years
2. Unified Schema: All data in single structure, differentiated by record_type
3. Events Not Pre-assigned: Events have NO pillar; effects via impact_links
4. Data Quality: Mix of high (surveys) and medium (estimates) confidence
5. Enrichment: Added infrastructure, gap, and market entry data
""")

print("Next Steps: Proceed to Task 2 - Exploratory Data Analysis")

======================================================================
TASK 1 COMPLETION SUMMARY
======================================================================

✓ Original Dataset: 43 records
✓ Enriched Dataset: 60 records (+17)
✓ Unique Indicators: 19
✓ Events Cataloged: 10

✓ Data quality documented
✓ Schema validation implemented
✓ Enrichment log created: data/processed/data_enrichment_log.md

======================================================================
KEY FINDINGS:
======================================================================

1. Limited Historical Depth: Only 5 Findex survey points over 13 years
2. Unified Schema: All data in single structure, differentiated by record_type
3. Events Not Pre-assigned: Events have NO pillar; effects via impact_links
4. Data Quality: Mix of high (surveys) and medium (estimates) confidence
5. Enrichment: Added infrastructure, gap, and market entry data

Next Steps: Proceed to Task 2 - Exploratory Data Analysis